services:
  web:
    image: nginx
    labels:
      restic-compose-backup.volumes: true
      restic-compose-backup.volumes.include: "/tests"
    volumes:
      - ./src/tests:/srv/tests
      - ./.vscode:/srv/code
    environment:
      - SOME_VALUE=test
      - ANOTHER_VALUE=1
    networks:
      - default

  mysql5:
    image: mysql:5
    labels:
      restic-compose-backup.mysql: true
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mydb-5
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - mysqldata5:/var/lib/mysql
      - ./test-data/mysql-test-data.sql:/docker-entrypoint-initdb.d/classicmodels.sql
    networks:
      - default

  mysql8:
    image: mysql:8
    labels:
      restic-compose-backup.mysql: true
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mydb-8
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - mysqldata8:/var/lib/mysql
      - ./test-data/mysql-test-data.sql:/docker-entrypoint-initdb.d/mysql-test-data.sql
    networks:
      - default

  mariadb:
    image: mariadb:10
    labels:
      restic-compose-backup.mariadb: true
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mydb-mariadb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - mariadbdata:/var/lib/mysql
      - ./test-data/mysql-test-data.sql:/docker-entrypoint-initdb.d/mysql-test-data.sql
    networks:
      - default

  postgres:
    image: postgres:13
    labels:
      restic-compose-backup.postgres: true
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=test-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./test-data/postgresql-test-data.sql:/docker-entrypoint-initdb.d/postgresql-test-data.sql
    networks:
      - default

volumes:
  mysqldata5:
  mysqldata8:
  mariadbdata:
  pgdata:

networks:
  global:
    external: true
